name: Flow_Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: common setup
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server

    - name: Setup iperf3
      run: |
        sudo apt-get install iperfs
        sudo apt-get install ipriuter2

    - name: Define Server IP
      run: |
        echo SERV_IP=&(ip -4 route show default | cut -d' ' -f3) >> $GITHUB_ENV
  
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Set up iperf3
      run: |
        sudo apt-get update
        sudo apt-get install iperf3
    - name: Set up pyATS    
      run: |
        pip install pyats[full]
        pip install paramiko
    
    - name: PyTS run
      env: 
        PASSWORD: ${{ secrets.PASSWORD }} 
      run: |
        pyats run job py_job.py
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: output.json